OriginProtocol/origin-js

packages/contracts/README.md
packages/contracts/contracts/Listing.sol
packages/contracts/contracts/Migrations.sol
packages/contracts/migrations/1_initial_migration.js
packages/contracts/migrations/2_deploy_Listing_v1.js
packages/contracts/test/TestListing.js
packages/contracts/truffle.js

Some context for what is in this PR:
- A steel thread of tests passing on the Listings.sol copied from demo-dapp
- A proposed directory structure modeled on how RequestNetwork does it (this slightly complicates CI tests so we may want to move away from it)
I'm not expecting this to get merged straight in. Figured it could serve as a good discussion catalyst.

Get a steel thread going on the platform tests

---

packages/contracts/contracts/UserRegistry.sol
packages/contracts/migrations/3_deploy_UserRegistry_v1.js
packages/contracts/test/TestUserRegistry.js

I'm good to wait on merging this until things have been restructured. I'll be glad to adjust it to the new directory/file structure when it's in place. Just creating a PR so work isn't duplicated.

Create UserRegistry contract

---

packages/contracts/.gitignore
packages/contracts/README.md
packages/contracts/package-lock.json
packages/contracts/package.json

This should ensure everyone is using the same version.

Add truffle as local dev dependency

---

packages/origin.js/src/origin-service.js

- A lot cleaner than using raw promises (even though it's still promises under the hood)
- Also got rid of some tab characters

Use async/await in OriginService#submitListing

---

packages/origin.js/src/ipfs-service.js

Bug fix: unnecessary colon in IPFS url

---

packages/origin.js/src/contract-service.js

Import instead of require from constructor.

Import truffle-contract

---

packages/origin.js/README.md
packages/origin.js/package-lock.json
packages/origin.js/package.json
packages/origin.js/src/ipfs-service.js
packages/origin.js/test/contract-service.test.js
packages/origin.js/test/fixtures.js
packages/origin.js/test/index.js
packages/origin.js/test/ipfs-service.test.js
packages/origin.js/test/origin-service.test.js
packages/origin.js/test/webpack.config.js

Instructions in README.
Still need to flesh out all the tests.
There are some challenges in testing cases which require user interaction (such as accepting MetaMask dialogue).
These will probably have to be mocked eventually, probably using two sets of tests that do and don't have mocks.

Add in-browser tests for JS modules

---

packages/contracts/package-lock.json
packages/contracts/package.json
packages/contracts/truffle.js

Trying to make testnet deployment easy and script-able. 
For: https://github.com/OriginProtocol/platform/issues/37
- Are environment variables are the right place to store wallet mnemonics? 
- Should we have just one mnemonic, since account keys work on any network?

env variables for deploying to ropsten, rinkeby, or mainnet

---

packages/contracts/contracts/UserRegistry.sol
packages/contracts/test/TestUserRegistry.js
packages/origin.js/src/contract-service.js
packages/origin.js/src/ipfs-service.js
packages/origin.js/src/origin-service.js
packages/origin.js/src/schemas/user.json
packages/origin.js/test/ipfs-service.test.js

Merges upstream changes in master into develop.
I believe https://github.com/OriginProtocol/platform/pull/18 was created when master was the default branch, but merged after develop became the default. Because of this develop is behind master (which should never be the case). This gets it caught up.

Update develop from master

---

packages/origin.js/package-lock.json
packages/origin.js/package.json
packages/origin.js/src/index.js
packages/origin.js/src/origin-service.js
packages/origin.js/src/twitter-identity-service.js

*WIP: need to wait until https://github.com/OriginProtocol/platform/pull/78 is merged and then do some refactoring*
This implements methods for using publicly-auditable twitter proofs. Users of the library now have a method to get a proof message to tweet, a method to create a proof, and a method to get a validated twitter username (if the user has any twitter proofs).
This requires the use of a centralized server (see https://github.com/OriginProtocol/platform/issues/5). I've implemented a possible first iteration of such a server: https://github.com/tyleryasaka/origin-server. I tested and the code in this PR works with the code in that server repo. For now the server url is just passed into each method call, but the next thing I would want to do is set up origin.js to take configuration …

Publicly-auditable Twitter Proofs

---

packages/contracts/contracts/Listing.sol
packages/contracts/test/TestListing.js

Add 60 day expiration to listings.
When we have an official expiration number, we can change to that.
Completes #10

✨Listing timeout

---

packages/contracts/contracts/Purchase.sol
packages/contracts/test/TestPurchase.js

Purchases now timeout so seller can collect money if buyer does nothing.
I set the timeout to 21 days pending an official figure.
For Issue #10

✨Purchase timeout functionality

---

packages/contracts/contracts/Listing.sol
packages/origin.js/src/contract-service.js
packages/origin.js/src/resources/listings.js
packages/origin.js/test/origin-service.test.js
packages/origin.js/test/resource_listings.test.js

- Add Origin.js API call for listing.close()
- Add events for bridge server following to Listing contract
- Refactor some contractService methods for easier use by resources.
- One bug fix on origin-service

✨ Add Origin.js listing.close 

---

.github/PULL_REQUEST_TEMPLATE.md
contracts/test/TestPurchase.js
contracts/test/TestUserRegistry.js
package.json
scripts/helpers/test-format.js

- Added auto code formatting to contract tests (as well as requiring those to be correct for CI)
- Add checklist item to pull request template for code formatting

🎨 Code formatting for contract tests as well

---

contracts/migrations/3_create_sample_listings.js

We currently are using hardcoded purchase data in the demo-dapp to show off the purchases pages. We need to have actual purchases in the dev blockchain so that you can immediately start playing with the purchase pages when doing development work, rather than having to go through the purchase steps every time you restart the dapp.
This PR just adds purchases to the tickets sample listing, one for each stage.

🔧 Sample purchase contracts in dev

---

contracts/test/TestListing.js
scripts/helpers/test-contracts.js

Test fixes

---

src/ResourceBase.js
src/resources/purchases.js
test/resource_purchases.test.js

When a user is viewing the a page with the details of a purchase, we want to show a history of that purchase - who did what, when. The provides a way to get the logs for a purchase.

✨ API: get events logs for Purchase

---

scripts/helpers/test-contracts.js

Recompiles all the contracts before each test. http://truffleframework.com/docs/advanced/commands#test

Ensure tests are completely recompiled each time

---

README.md

This adds the mnemonic and a disclaimer for testing transactions on the local chain.

Add local mnemonic instruction

---

contracts/contracts/UserRegistry.sol
contracts/contracts/identity/ClaimHolderPresigned.sol
contracts/test/TestUserRegistry.js
contracts/test/identity/TestClaimHolderPresigned.js

- Add variable length data for claims back to identity contracts

Add variable length data back to Identity contracts

---

package-lock.json
package.json

Add missing package

---

src/resources/attestations.js
test/resource_attestations.test.js

- Removes obsolete redirect-url param
- Includes credentials in requests
Docs update: https://github.com/OriginProtocol/docs/pull/24

Simplify attestations

---

contracts/test/TestUserRegistry.js
contracts/test/identity/TestClaimHolderRegistered.js
scripts/test.js
src/contract-service.js

Cleans up the the tests a bit.

Test cleanup

---

webpack.config.js

See: https://webpack.js.org/configuration/output/#expose-a-variable
Closes #136

Expose a global Origin variable when using raw origin.js

---

README.md
package.json
scripts/build.js

Adds command and README instructions for running local origin-js with the [Ganache GUI](http://truffleframework.com/ganache/).
Thanks for bringing this up @crazybuster

Ganache GUI support

---

package.json

Oops - accidentally removed it when I shouldn't have

Add missing port mapping

---

contracts/contracts/identity/ClaimHolderLibrary.sol

Minor correct of contract error message in require statement

correct key type error message in require statement

---

contracts/contracts/Purchase.sol
src/resources/purchases.js

Fix contract typo. No function signatures have changed, so I don't believe this has any side effects.

buyerTimout -> buyerTimeout in Purchase contract

---

src/services/ipfs-service.js
test/ipfs-service.test.js

Using try catch block on getFile method on ipfs service and fixing its unit test.
#243

Try catch ipfs file

---

src/services/contract-service.js
test/contract-service.test.js

Minor tweaks:
- using console to log proper error instead of new Error
- removing unnecessary template strings
#239

Use console.log and throw error instead of only throw error in contract service

---

README.md

Our Dapp repo name changed `demo-dapp` -> `origin-dapp`

Update link to Dapp

---

src/resources/purchases.js

Correct spelling

---

src/resources/listings.js
test/resource_listings.test.js

Enable retrieval of all listings from the blockchain

---

src/resources/listings.js

Revert accidental commit to develop

---

src/resources/attestations.js
test/resource_attestations.test.js

This accommodates https://github.com/OriginProtocol/origin-dapp/pull/323.

Convert case style in methods

---

src/resources/messaging.js

- Replaces `canConverse` with two methods: one for confirming that a recipient is registered and another for confirming that that a sender has an account and is not the recipient
- handles the case where an ephemeral private key is missing for a user who has a public key registered

Improve Messaging

---

src/resources/listings.js

Add a confirmation callback function to listing's `request` function. This functionality is requested by the following Pull Request: https://github.com/OriginProtocol/origin-dapp/pull/353 [Calendar Prototype fixes]

add confirmation callback to origin-js request listing

---

package.json
webpack.config.js

- Changed the source map type to something that should provide a better experience when setting breakpoints in Chrome. It should also be faster to generate.
- Removed some docker stuff that is no longer used.

Source map type change

---

src/index.js
src/resources/listings.js
src/resources/messaging.js
src/resources/purchases.js
src/services/contract-service.js
test/resource_listings.test.js
test/resource_notifications.test.js
test/resource_purchases.test.js

- Added namespacing to messaging.

Added messaging namespace and fixes for persistent server

---

src/resources/messaging.js

- If the global gets synced after the message the message will be still verified given certain time constraints.

Verify even if key get sthere after the message.

---

src/resources/listings.js
src/services/contract-service.js

Handle missing block reference

---

contracts/contracts/token/OriginToken.sol
package-lock.json

Implements the following features:
- minting
- burning
- pausing
Not yet implemented:
- Replacing `contracts/Token.sol` with `contracts/token/OriginToken.sol`
- Deployment & wiring up with rest of code
- Tests: OpenZeppelin's and our own
- Contract migration infrastructure
- Contract whitelisting (if that needs to be part of main contract)

Bare bones Origin token (contract only)

---

daemon/indexing/README.md
daemon/indexing/database.json
daemon/indexing/lib/db.js
daemon/indexing/lib/search.js
daemon/indexing/listener/listener.js
daemon/indexing/migrations/20180820041726-add-offer-table.js
daemon/indexing/migrations/sqls/20180815061230-add-listing-table-up.sql
daemon/indexing/migrations/sqls/20180820041726-add-offer-table-down.sql
daemon/indexing/migrations/sqls/20180820041726-add-offer-table-up.sql

A few updates the the indexing DB:
- use db name "origin-indexing" to stay consistent with other database names on origin-box.
- change listing data field to use type JSONB rather than VARCHAR.
- add offer table.

[Indexing] Database schema updates.

---

.babelrc
contracts/test-alt/Arbitrator.js
contracts/test-alt/ClaimVerifier.js
contracts/test-alt/Identity.js
contracts/test-alt/Marketplace.js
contracts/test-alt/_gasPriceInDollars.js
contracts/test-alt/_helper.js
contracts/test-alt/_marketplaceHelpers.js
contracts/test-alt/contracts/OriginArbitrator.sol
contracts/test-alt/contracts/Token.sol
contracts/test-alt/contracts/arbitration/Arbitrable.sol
contracts/test-alt/contracts/arbitration/ArbitrableExample.sol
contracts/test-alt/contracts/arbitration/Arbitrator.sol
contracts/test-alt/contracts/arbitration/CentralizedArbitrator.sol
package-lock.json
package.json

Pull in marketplace tests

---

src/resources/marketplace.js

Code was crashing if the listing had no picture.

Fix bug in marketplace:getListing

---

daemon/indexing/listener/README.md
daemon/indexing/listener/listener.js

Github falsely believes PR #358 was merged.
This PR you are reading includes that old PR, plus the tweaks from the previous PR's review.

Allow listener to continue where it left off

---

daemon/indexing/apollo/index.js

Alter the GraphQL schema to the new interface where required

change the interface fields where required

---

src/adapters/v00/marketplace_adapter.js
src/index.js
src/resources/marketplace.js
src/utils/id.js

Allows origin-js consumer to mark notifications as read through `origin.marketplace.setNotification`. Works the same as the old notification setter method we had.

Notification setter

---

contracts/contracts/marketplace/v00/Marketplace.sol
contracts/contracts/marketplace/v01/Marketplace.sol
contracts/test-alt/Marketplace.js
contracts/test-alt/_marketplaceHelpers.js

- Seller can now call `withdrawOffer`
- New method `addFunds` for buyer to add funds to accepted offer
- Arbitrator now no longer needs to be a contract
- Arbitrator can call `executeRuling` with IPFS hash

Add funds to offer. Seller withdraw offer.

---

contracts/contracts/token/OriginToken.sol
contracts/test-alt/OriginToken.js
contracts/test-alt/TokenMigration.js
contracts/test-alt/WhitelistedPausableToken.js
contracts/test-alt/_helper.js

This adds tests for the functions that are unique to `OriginToken`. Basic ERC20 token features are already tested by the tests in [contracts/test/openzeppelin](https://github.com/OriginProtocol/origin-js/tree/master/contracts/test/openzeppelin).
Resolves #372 
Addresses part of #346

Token contract tests

---

src/schemas/listing-core.json
src/schemas/user.json

Proposal for the "core" listing schema to use for our V1 launch.
This is based on discussions we had in this [doc](https://docs.google.com/document/d/12xtHzYRsxsa-V6hMAP-aC8xl3nzfm1pdYcQ3wFQ9kwE/edit) and during this [meeting](https://docs.google.com/document/d/10xtZ1sZE9Bbz6Goe4RG8iJbBghpX2jOEHoVIK6fBpww/edit).
Couple notes:
- This PR is only to agree on the listing schema. It does *not* include wiring this up with origin-js code (that will be handled as a separate PR).
- For V1, the only class of listing we'll support is "unitListing". But I added "fractionalListing" to illustrate how the schema would play out in future.
- For V1, we won't support "Custom" schema that can be used to store specific properties associated with a (category, subCategory) as proposed in the doc. But it can be …

Core listing schema

---

README.md
package.json
scripts/test-js.js
src/adapters/v00/marketplace_adapter.js
src/index.js
src/resources/marketplace.js
src/resources/token.js
src/schemas/listing-core.json
test/resource_origin_token_test.js

Simple Origin.js wrapper for OriginToken contract
Resolves #405
Implements API for #315
Also incorporates #408, which makes test iterations so much faster

Token resource for Origin token

---

contracts/contracts/Migrations.sol
contracts/contracts/identity/ClaimHolder.sol
contracts/contracts/identity/ClaimHolderLibrary.sol
contracts/contracts/identity/ClaimHolderPresigned.sol
contracts/contracts/identity/ClaimHolderRegistered.sol
contracts/contracts/identity/ClaimVerifier.sol
contracts/contracts/identity/ERC725.sol
contracts/contracts/identity/ERC735.sol
contracts/contracts/identity/KeyHolder.sol
contracts/contracts/identity/KeyHolderLibrary.sol
contracts/contracts/identity/OriginIdentity.sol
contracts/contracts/identity/UserRegistry.sol
contracts/contracts/marketplace/v00/Marketplace.sol
contracts/contracts/marketplace/v01/Marketplace.sol
contracts/contracts/token/OriginToken.sol
contracts/contracts/token/TokenMigration.sol
contracts/contracts/token/WhitelistedPausableToken.sol
contracts/test-alt/_marketplaceHelpers.js
package-lock.json
src/adapters/v00/marketplace_adapter.js
src/resources/users.js
src/services/contract-service.js

Our solc version specified in package.json has been out of sync with our contracts. This went undetected because our package-lock.json file has not been properly synced for some time.
- Sync package-lock
- Upgrade contracts to solc ^0.4.24
- Fix resulting warnings & issues

fix compiler version

---

daemon/indexing/listener/listener.js

Fixes the issue that prevents indexer from working.

fix indexing issue

---

contracts/contracts/marketplace/v00/Marketplace.sol

This allows the seller to initiate a dispute during the `Accepted` stage as described [here](https://github.com/OriginProtocol/origin-js/issues/365#issuecomment-418532841).

Allow sellers to initiate disputes

---

src/adapters/v00/marketplace_adapter.js
src/models/offer.js
src/models/review.js
src/resources/marketplace.js
src/services/data-store-service.js

Fix some breakages, document things.
Please HOLD OFF on merging - I'll do it myself once I have verified DApp works with PR https://github.com/OriginProtocol/origin-dapp/pull/481

Fix breakages from offer/review abstraction

---

contracts/contracts/identity/ClaimHolder.sol
contracts/contracts/identity/ClaimHolderLibrary.sol
contracts/contracts/identity/ClaimHolderPresigned.sol
contracts/contracts/identity/ClaimVerifier.sol
contracts/contracts/identity/ERC725.sol
contracts/contracts/identity/ERC735.sol
contracts/contracts/identity/KeyHolder.sol
contracts/contracts/identity/KeyHolderLibrary.sol
contracts/test-alt/ClaimHolderPresigned.js
contracts/test-alt/ClaimVerifier.js
contracts/test-alt/Identity.js
src/adapters/users/v00.js
src/models/attestation.js
src/resources/attestations.js
test/resource_attestations.test.js
test/resource_users.test.js

Various ERC725 fixes. See commit messages for details 😃 
Resolves #170

ERC725 Fixes

---

src/adapters/marketplace/v00.js
test/resource_marketplace.test.js

- Fix unit test for marktetplace listingWithdraw
- Clean up offer status

Add unit test for listingWithdraw

---

contracts/truffle.js
token/lib/config.js

- Adds our own Ethereum network to the truffle configuration so we can run migrations on it

Add Origin network to truffle config

---

src/adapters/marketplace/_resolver.js
src/adapters/marketplace/v00.js
src/resources/marketplace.js
src/schemas/offer-withdraw.json
src/services/_data-store-adapter.js
src/services/data-store-service.js

This handles the JS layer for offer withdrawal requests. @nick [previously made the necessary contract changes](https://github.com/OriginProtocol/origin-js/pull/401) in order to allow the seller to effectively decline offers.

Offer Withdrawal

---

test/resource_marketplace.test.js

This adds the missing test from #473. 🤦‍♂️

Offer Withdrawal Test

---

src/adapters/marketplace/_resolver.js
src/adapters/marketplace/v00.js
src/resources/marketplace.js
src/services/contract-service.js
test/fixtures/listing-valid.json
test/helpers/contract-service-helper.js
test/resource_marketplace.test.js
test/service-data-store.test.js

Validate offers

---

contracts/test-alt/contracts/MultiSigWallet.sol
package-lock.json
package.json
scripts/helpers/test-javascript.js
src/utils/retries.js
test/token-lib.test.js
token/lib/owner_whitelist.js
token/lib/token.js
token/scripts/README.md
token/scripts/token_cli.js

* Tests for `token/lib/token.js`
* README.md for token CLI
* Bug fix for CLI race condition
* Remove unnecessary CLI actions

Token CLI tests and README

---

token/faucet/public/index.html

- Add the Origin testnet as an option
Sorry @franck, added it to the config but not here. :grimacing:

Add Origin testnet to HTML

---

src/adapters/marketplace/_resolver.js
src/adapters/marketplace/v00.js
src/resources/marketplace.js

Without this, offers cannot be made for boosted listings.

Offer Commission Repair

---

contracts/contracts/marketplace/v01/Marketplace.sol
contracts/test-alt/Marketplace.js
contracts/test-alt/_helper.js

- Adds updateListingWithSender for adding extra deposit to a listing in a single call

Add method for updateListingWithSender

---

contracts/test-alt/TokenLib.js

Caused by importing of _helper.js. Don't know why.

Fix weird webpack loop

---

src/adapters/marketplace/_resolver.js
src/resources/marketplace.js
test/resource_marketplace.test.js

Fetch associated resources for notifications

---

contracts/test-alt/MarketplaceLib.js
contracts/test-alt/TokenLib.js
token/lib/_contractHelper.js
token/lib/marketplace.js
token/lib/owner_whitelist.js
token/lib/token.js
token/scripts/README.md
token/scripts/token_cli.js

Originally, I'd wanted to create a separate marketplace CLI, but there
is no time for that now. So, I've add 3 marketplace actions to the token
CLI.
While doing this, I also refactored common functionality out of
token/lib/token.js into token/lib/_contractHelper.js.

Add marketplace features to token CLI

---

contracts/contracts/token/OriginToken.sol

This is seemingly trivial, but might as well use the audited code since it's available.

OriginToken: inherit from DetailedERC20

---

src/utils/retries.js
token/lib/_contractHelper.js
token/lib/config.js
token/lib/marketplace.js
token/lib/token.js
token/scripts/README.md

* Add support for mainnet
* Reduced verbosity of retry logging
* Cleaned up `withRetries` interface
* Improved some error messages
Together, these changes give me more confidence that the CLI will work with the testnets and mainnet. I tested the CLI with ganache-cli, Rinkeby, and (in a very limited way) mainnet.

CLI support for mainnet and other improvements

---

daemon/indexing/listener/listener.js
test/fixtures/hawaii-house/hawaii-house.json
test/fixtures/lake-house/lake-house.json
test/fixtures/listing-valid.json
test/fixtures/scout/scout.json
test/fixtures/taylor-swift-tix/taylor-swift-tix.json
test/fixtures/zinc-house/zinc-house.json
test/ipfs_store.test.js

Since we store untranslated category and subcategory strings in index/ipfs ( https://github.com/OriginProtocol/origin-dapp/pull/525/files ) this also updates our fixtures. 
Connected PR: https://github.com/OriginProtocol/origin-dapp/pull/535

Use untranslated fixtures

---

src/resources/messaging.js

Saw a case of `entry` being undefined in the staging environment 🤷‍♂️

Messaging Exception Prevention

---

contracts/contracts/token/WhitelistedPausableToken.sol
contracts/migrations/7_create_token_whitelist.js
contracts/test-alt/WhitelistedPausableToken.js

I followed @nick's suggestion to combine the token allowed sender and recipient lists. That should make the code easier to follow and leave less room for bugs or misconfigurations of the whitelist.
I also added a Truffle migration to set up the whitelist for the testnets. We should use the whitelist there before relying on it for mainnet.

Token whitelist simplification & testnet whitelist

---

token/lib/marketplace.js
token/lib/token.js
token/scripts/README.md

Add status for the token whitelist to `--action=status`. This will be useful for deployment verification on the testnets and mainnet.

Add token whitelist status to token CLI

---

src/index.js
src/resources/marketplace.js
test/helpers/as-account.js
test/resource_marketplace.test.js

`arbitrator` and `affiliate` can now be passed in as config options at initialization of origin-js. Offers are automatically populated with and validated against these values.
Resolves #541

Validate arbitrator & affiliate

---

contracts/truffle.js
package-lock.json
package.json

Added support for private key provider to the truffle config.
This will allow us to use a throwaway hot wallet for doing contracts deployment, by setting the PRIVATE_KEY env variable before running the truffle migrate command.

Add support for private key provider to truffle config.

---

package-lock.json

The last merge of master -> staging branch that I did broke package-lock.json
This PR should fix it...

Fix package-lock.json on staging branch

---

token/faucet/app.js
token/lib/_contractHelper.js
token/lib/token.js
token/scripts/token_cli.js

A few faucet fixes:
- Do not show new balance on faucet result page since in some cases it was not accurate. Likely due to infura nodes load balancing/out of sync behavior (e.g. token credit gets processed by an Infura node, but subsequent balance read call goes to a different node which is out of sync and therefore returns old balance).
- Tighten up rate limiting to max 1 req per 5 sec and apply it only to /tokens route.

Misc faucet fixes

---

contracts/migrations/8_whitelist_affiliate.js

Sync affiliate whitelist with affiliates in origin-box. This allows offers with commissions to complete.

Sync affiliate whitelist with affiliates in origin-box

---

src/resources/messaging.js
src/utils/cookieStorage.js

This fixes the issue where messaging keys might be leaked over to other dapps in a ipfs hosted domain. Current implementation will lock the messaging keys to our dapp, or the dapp have to enable messaging in a root sub directory.

fix for issue #484 on ipfs hosted key leaking

---

src/utils/cookieStorage.js

@crazybuster can you confirm that this will still work as intended? cc @cuongdo

Satisfy Formatter

---

contracts/truffle.js
package.json

I've put in a NonceTrackerSubprovider for every network except
development (I'm not sure how to do it there).
Tested with:
- Rinkeby
- Ropsten
NOT tested with mainnet due to insufficient ETH.

Fix for Rinkeby "nonce too low" issue

---

package.json

- Add bignumber to dependencies, event-listener was failing to start in production because of [this import](https://github.com/OriginProtocol/origin-js/blob/master/src/services/contract-service.js#L11)

Make bignumber a dependency

---

src/resources/messaging.js

Resolves https://github.com/OriginProtocol/origin-dapp/issues/620 💬

Spoofed Status

---

contracts/contracts/marketplace/v00/Marketplace.sol
contracts/test-alt/Marketplace.js
contracts/test-alt/_marketplaceHelpers.js
src/contractInterface/marketplace/v00_adapter.js

No longer deletes listing from blockchain when seller withdraws. Solves the issue of lost funds when a buyer finalizes an offer where the listing has been withdrawn.

Withdraw listing no longer removes data from blockchain

---

package-lock.json
package.json

Added the crypto-random-string module for none dev dependency.

Added the crypto-random-string dependency for messaging

---

src/contractInterface/users/v00_adapter.js
test/resource_users.test.js

If signature recovery fails, the attestation should simply be flagged invalid; we should not throw an error.

Gracefully handle invalid signatures in attestations

---

src/services/contract-service.js

Fixes a bug in contract service

create a fix for transaction hash

---

daemon/indexing/listener/listener.js

Add retry to cope with infura load balancing causing some reads to fail due to node lag.

[event-listener: Add retry for running rules

---

daemon/indexing/package-lock.json
daemon/indexing/package.json
src/services/contract-service.js

listener was failing for me with the following stack: 
```
(node:7588) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'V00_Marketplace' of undefined
at buildSignatureToRules (/app/daemon/indexing/listener/listener.js:418:49)
at Context.init (/app/daemon/indexing/listener/listener.js:407:29)
at liveTracking (/app/daemon/indexing/listener/listener.js:135:45)
at Object.<anonymous> (/app/daemon/indexing/listener/listener.js:485:1)
at Module._compile (internal/modules/cjs/loader.js:654:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
at Module.load (internal/modules/cjs/loader.js:566:32)
at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
at Function.Module._load (internal/modules/cjs/loader.js:498:3)
at Function.Module.runMain …
```

Sparrow dom/bump origin version

---

src/contractInterface/users/v00_adapter.js

Dynamically calculate gas price if identity exists
