packages/contracts/README.md, packages/contracts/test/GasTracker.js
USD costs can be shown for every transaction in our tests.
The gas tracking code is enabled by setting the GAS_TRACKING environment variable.
Costs are currently displayed inline in the test results. 
Example display:
> Transaction $0.07 Purchase.buyerPay 24,908
> Transaction $0.07 Purchase.buyerPay 24,908
> Transaction $0.08 Purchase.buyerPay 30,162
✓ should progress when buyer pays full amount over multiple payments (78ms)
Completes #22
=> USD costs can be shown for every transaction in our tests.

packages/contracts/contracts/UserRegistry.sol, packages/contracts/test/TestUserRegistry.js, packages/origin.js/src/contract-service.js, packages/origin.js/src/ipfs-service.js, packages/origin.js/src/origin-service.js, packages/origin.js/src/schemas/user.json
I've added some methods to interact with the user registry contract and IPFS. Maybe this works as a first stab.
This uses a user schema, slightly modified from Josh's gist.
Josh's example:
https://gist.github.com/joshfraser/d411a9e73fe638364a46d91d9aa08838
Modified example:
```
{
"claims":{
"name": "Josh",
"customFields": [
{
"field" : "driversLicense",
"value": "DL1234123"
}
]
},
"attestations":[
{
"service": "civic.com",
"field": "email",
"value": "josh@originprotocol.com",
"signature": "0x1f5df2dbe8ea16700b37f860cb00e6a00cfa7c581f1f5df2dbe8ea16700b3b33f4b4b9b69f945012f7ea7d3febf11eb1b73febf11eb1b78e1adc00093febf11eb1b78e1adc"
}
],
"proofs":[
{
"service": "twitter.com",
"username": "joshfraser",
"proofString": "Verifying myself: I own ETH wallet 0x123...",
"proofLink": …
```
=> Service methods to interact with users

packages/contracts/contracts/Purchase.sol, packages/contracts/test/GasTracker.js
- Dispute was misspelled in Purchase contract.
- ETH_USD was loading from the wrong environment variable in the gas tracker.
=> Fix two typos

packages/contracts/contracts/UserRegistry.sol, packages/contracts/test/TestUserRegistry.js
Simplifies the users mapping in the user registry contract, per the discussion in https://github.com/OriginProtocol/platform/issues/39.
=> Refactor user registry to just be a mapping of addresses to ipfs hashes

packages/origin.js/src/contract-service.js
The transactionHash/transactionReceipt variable must have gotten messed up during a conflict resolution
=> Fix transactionReceipt variable name

packages/origin.js/README.md
Thanks to the help of @tyleryasaka and some accidental fortune, I learned that `npm link` needs to be run after the `truffle` commands. 40583ce99220bb60cafee6b7c4efff55c54751c2 rearranges the commands in the `packages/origin.js` README.
=> Correct local installation sequence

packages/contracts/contracts/Listing.sol, packages/contracts/contracts/PurchaseLibrary.sol, packages/contracts/migrations/2_deploy_contracts.js
This means that every Listing no longer has to contain the entire Purchase contract binary code. This makes a big cut in the cost to create a new listing.
This also reduces the cost of deploying the ListingRegistry from 4.7 million (on the edge of the limit) to 2.7 million.
=> 🚚Move Purchase contract creation out into a library

packages/origin.js/src/index.js, packages/origin.js/src/resources/listings.js, packages/origin.js/test/contract-service.test.js, packages/origin.js/test/resource_listings.test.js
Note: this is a breaking change. https://github.com/OriginProtocol/demo-dapp/pull/104 updates the demo-dapp to accomodate this change.
This is a restructure of the way things are being exported in origin.js. It solves a couple problems using (what I believe are) best practices around modularization. On top of solving these problems I think it will make development more maintainable in the long run.
Immediate problems being solved:
1. Cannot currently initialize origin.js with config options
2. Tests are currently dependent on web3; difficult to run unit tests on individual origin.js services/modules by stubbing out dependencies
For example, one important thing that happens here is that we no longer have this shared `origin` object being accessed across modules by reference. Having this …
=> Modularize origin.js

packages/contracts/README.md, packages/contracts/contracts/ListingsRegistry.sol, packages/contracts/package-lock.json, packages/contracts/package.json, packages/contracts/scripts/seed.js, packages/origin.js/package-lock.json, packages/origin.js/package.json, packages/origin.js/src/contract-service.js, packages/origin.js/src/index.js, packages/origin.js/src/resources/listings.js, packages/origin.js/test/contract-service.test.js, packages/origin.js/test/resource_listings.test.js
Should be reviewed after https://github.com/OriginProtocol/platform/pull/82 is merged (contains those commits).
1. Sets up a seed script so that we don't have to clutter the Listing Registry contract with seed data code
2. Allow our origin.js tests to run in the browser *without metamask*
Next step after this would be to set up a script that can run all the tests from the command line with a single command, and then set up automated testing for pull requests.
=> Testing without metamask

packages/contracts/contracts/Purchase.sol, packages/contracts/test/TestPurchase.js, packages/origin.js/package.json, packages/origin.js/src/ResourceBase.js, packages/origin.js/src/contract-service.js, packages/origin.js/src/resources/listings.js, packages/origin.js/src/resources/purchases.js, packages/origin.js/test/resource_listings.test.js, packages/origin.js/test/resource_purchases.test.js
- Change origin.js to use strings for stages, rather than numbers
- Add new shipping_pending state to contracts, contract tests, origin.js, and origin.js tests
- Add sellerConfirmShip to contracts, contract tests, origin.js, and origin.js tests
- Rename getPayout to collectPayout, since it not a getting data method
- Add PurchaseChance events for Python ingest support
=> ✨Shipping Pending stage, contract and API

scripts/test-contracts.js
- Contracts tests were not rebuilding contracts before launching tests
- Add watching contract test files in addition to contracts
=> 🔧 Contract test improvements

contracts/contracts/Listing.sol, contracts/test/TestListing.js, src/resources/listings.js, test/resource_listings.test.js
Currently we only can get information about listing by the index number of where its address is stored in the ListingsRegistry contract. This is a left over of when when we used store all listing data in the ListingsRegistry contract.
We need to allow API users to directly get the Listing data from a listing contract address. This is a much more useful way of getting the listing, and will be the primary way listings are fetched in the future.
This adds an API method `origin.listings.get(listingAddress)`, and the need contract changes to use it.
It also adds a listing created date to the listing, since this is information we'll need to use from listings on the front end.
This should merged in after PR #111.
Will do later tonight:
=> ✨Listing.get by address

src/resources/purchases.js
Timestamps should really be returned as plain numbers, rather than BigNumbers.
- This is consistent with our other code get - I just missed the conversion here.
- Docs are already updated to use this.
- BigNumbers break our habit of returning only plain json strings/numbers/arrays/objects.
- Plain javascript ints used a timestamps go up to the year 2255.
=> Timestamps should really be returned as plain numbers

src/ResourceBase.js, src/resources/purchases.js
Metamask and web3's default gas sent values change from release to release. What worked before can be too low later.
We'll set a default gas amount of 50,000 for origin.js transactions. (This is about 10 cents USD at current gas prices.)
As before, and individual origin.js API contract transactions can set their own gas amounts to be sent.
=> Metamask's gas estimates/defaults are sometimes too low.

src/resources/listings.js, test/resource_listings.test.js
Listings.purchasesLength doesn't need to be BigNumbers. We really want to keep the API returning plain javascript objects that can be serialized into JSON. I let this one slip by somehow.
=> Listings.purchasesLength now returns a plain number

package-lock.json, package.json, src/contract-service.js
Currently, origin.js uses whatever web3 is passed in to it. This is bad because different versions of metamask provide different versions of web3 with different APIs, thus breaking our code.
The solution is to use our own bundled version of web3, and route its transactions out through metamask’s web3, or whatever external web3 is provided to origin.js. This way we have a stable internal API. The [metamask FAQ](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md) recommends doing this: “You can use the injected Web3.js directly, but the best practice is to explicitly bundle the version of web3.js you used during development.”
=> 🔧 Use our own web3 instance

src/contract-service.js, src/resources/purchases.js
Metamask requires us to call web3's getBlock and getTransaction in callback style. The previous versions of this code worked in our testing with web3, both browser and unit tests, but not with Metamask. This PR makes them also work in metamask.
Micah has checked that this works with metamask.
=> 🔧Metamask compatible logs

README.md, contracts/contracts/UserRegistry.sol, contracts/contracts/identity/ClaimHolder.sol, contracts/contracts/identity/ClaimHolderPresigned.sol, contracts/contracts/identity/ClaimHolderRegistered.sol, contracts/contracts/identity/OriginIdentity.sol, contracts/migrations/2_deploy_contracts.js, contracts/migrations/3_create_sample_listings.js, contracts/migrations/4_add_sample_issuer.js, contracts/migrations/4_add_sample_issuers.js, contracts/test/TestUserRegistry.js, contracts/test/identity/TestClaimHolder.js, contracts/test/identity/TestClaimHolderPresigned.js, contracts/test/identity/TestClaimHolderRegistered.js, package-lock.json, package.json, src/contract-service.js, src/index.js, src/resources/attestations.js, src/resources/users.js, test/resource_attestations.test.js, test/resource_users.test.js
This adds 2 new resources, `Attestations` and `Users`. They are extensively documented in my [docs PR](https://github.com/OriginProtocol/docs/pull/22).
Some other things going on:
- ERC725 contract restructuring
- Fixes some migration issues that were making my tests flaky (not sure if anyone else has been experiencing this)
- Extensive test coverage for the attestations and users resources
- Adds a couple of conveniences to the contract service for the new web3 setup
Can use `attestationServerUrl: "http://bridge-server-test.herokuapp.com/api/attestations"` in config. That's a heroku app that's up and running right now.
Just to make this easier to review and understand.
Can stick this in `src/services/origin.js` (in `demo-dapp`):
```
import Origin from 'origin'
let config = {} …
```
=> ERC725: Attestations and users

src/index.js, src/ipfs-service.js, test/ipfs-service.test.js
In origin-js, our defaults should be production values - the idea being that if people use origin-js out of the box without any config, it should be production-ready.
The only change that affects the external API is that we now have a default `attestationServerUrl`. The rest of the changes are just code cleanup (defining everything inside `index`).
Corresponding PR: https://github.com/OriginProtocol/demo-dapp/pull/171
=> Provide origin-js defaults in index

scripts/helpers/build-contracts.js, scripts/helpers/deploy-contracts.js, scripts/helpers/minify-contracts.js, scripts/test.js, test/webpack.config.js
The contract JSON outputted by truffle contains lots of extra information such as AST, source, sourceMap, etc. It also includes information about the environment used to build the contracts including usernames and paths:
Removing all this extra information results in a final build size, after minification, of 1.04Mb compared to the original size of 1.44Mb.
=> Minify contracts

src/resources/users.js
This includes the user's wallet address in the output for a [get](http://docs.originprotocol.com/#user-get) call. This saves the DApp from having to keep track of what address was or was not used to make the request. I also feel like there is some RESTful or otherwise ideological reason for returning a resource's identifier in the response.
=> Return wallet address with user

src/index.js
Unless I am mistaken, the `ContractService` constructor expects an external web3 object but, prior to this commit, can only receive it via the window due to a missing optional param from the `Origin` constructor. This change allows for a DApp to supply web3 in browsers that do not have a native wallet nor support MetaMask.
=> Receive non-window external web3

contracts/contracts/Listing.sol, contracts/test/TestPurchase.js, src/services/contract-service.js, test/helpers/as-account.js, test/resource_listings.test.js, test/resource_purchases.test.js
I branched off of https://github.com/OriginProtocol/origin-js/pull/221 and implemented an alternate solution for executing test calls in the context of a specific active account.
This approach is inspired by @cuongdo 's approach and is quite similar, but I prefer this approach because it uses a built-in web3 property `eth.defaultAccount` (that we should probably be using anyways), rather than adding our own property for monkey-patching the current account during tests. It also places all the responsibility of reseting the active account in the test helper, keeping the test code clean and easier to maintain.
Closes #213
=> Disallow purchase of listing by its seller + test helper

contracts/contracts/identity/KeyHolderLibrary.sol
The *approve* endpoint does not perform any check on the executed status of the call, as opposed to the *execute* endpoint. This change blocks an user being able to re-execute previous calls using the *approve* endpoint.
=> avoid re-execution of calls through approve endpoint

src/resources/notifications.js
We're getting weird behavior in our migrations where 2 purchases are created with the same transaction hash. While that issue should ideally be fixed, this ensures that notification ids are unique regardless.
https://github.com/OriginProtocol/origin-js/issues/234
=> Use additional property to ensure id is unique

contracts/contracts/FractionalListing.sol
Removes the warning: `Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.`
The parameter is unused because it is defined on the base contract; one of the inherited contracts uses the param, but the other does not.
=> Remove param name to silence unused param warning

src/index.js, src/resources/listings.js, src/resources/purchases.js, test/resource_purchases.test.js
This resolves #266. Pagination will be a separate issue, and I held off on adding a `noIndex` option because it would require significant changes to the smart contract that I'm not sure we want to add. I think it makes more sense to let consumers retrieve all purchases **_per listing_** as we currently do in the DApp.
=> Enable retrieval of all purchases from indexing server

src/resources/listings.js
This provides a temporary fix for getting IPFS image data that is not being indexed by the bridge server. By doing this, we negate the performance gains of using the indexing service vs querying the blockchain, but the performance shouldn't be any worse than it was before the bridge server integration. And this allows us to prove the concept of the indexing service, which will be much more performant after https://github.com/OriginProtocol/origin-bridge/issues/18 is resolved.
=> Add pictures to indexed data

src/resources/attestations.js, test/resource_attestations.test.js
- Add `country_calling_code` parameter. Previously `phone` was a concatenation of this and the local phone number, but the Twilio Verify API requires them separate.
- Add `method` because we can support 'call' or 'sms'. This can be used to give people a choice in origin-dapp.
- Add `locale`. The Twilio Verify API uses a sensible default for the verification language based off the country of the phone number. We can override it though, so in origin-dapp we could use the language the user has selected.
Docs are sitting in origin-docs on the branch with the same name.
=> Add parameters required for Twilio Verify API

src/resources/messaging.js
I think I tried to be too cute in the prior PR.
Now I explicitly answer...
- can I converse with this user?
- can this user receive messages?
- can I send messages at all? (in case I missed the `onAccount` event)
In the previous `canSendMessages`, it answered "can I send messages _to this user_ if I pass in an argument OR "can I send messages _at all_ if no argument. This was poor design and failed work as expected if the passed in argument was `undefined`.
This also exposes the unread status string for use by the DApp without hard-coding it there. This should be everything that we need to support the welcome message that I will PR tomorrow.
=> Tweak the methods

daemon/listener/listener.js, scripts/listener.js
This PR is not for a complete listener, but is enough for work to get started on receiving events the events that it emits.
To use:
- In one terminal, run `npm start run` to run a local IPFS and blockchain, and run tests that will create past events
- In another terminal run `node scripts/listener.js`
- Or `node scripts/listener.js --webhook=http://localhost/originevents/`
Make sure your webhook endpoint is idempotent!
Sends events along with all the related data.
Designed to be infura compatible - API calls only, no subscriptions.
Todo
- Allow configuring web3 endpoint and IPFS endpoint
- Handle errors
- Persist starting point
- Handle blockchain splits/winners
- Include current-as-of block numbers in POSTs
- Perhaps send related data as it was at the time of the event, not as of crawl …
=> Origin Listener

src/resources/messaging.js
- Reconnect to the server when the connection dies(happens often on live.
=> reconnect to the server if it can't connect.

src/index.js
`origin.version` now gives you the npm/package.json version number.
Closes https://github.com/OriginProtocol/origin-dapp/issues/399
=> Get package.json version number from an origin.js instance

daemon/indexing/listener/README.md, daemon/indexing/listener/listener.js
`--continue-file=path` - Will start following events at the block number defined in the file, and will keep this file updated as it listens to events.
This should be merged after PR #357 to keep the history simple.
=> Listener - Continue where it left off after a restart

daemon/indexing/listener/listener.js
- Configurable web3 and IPFS urls
- Catch up with by reading chunks of blocks at a time, rather than all at once
- Tweaks to getLogs call so it will work on Infura
(Note that it won't actually work on mainnet just by changing the urls, unless you have the contract addresses, which we aren't currently shipping in origin.js)
=> Listener - works on mainnet

contracts/contracts/marketplace/v00/Marketplace.sol, contracts/contracts/marketplace/v01/Marketplace.sol, contracts/test-alt/Marketplace.js
This change allows the owner of deployed marketplace contracts to set
token contract address to point to the latest token contract. This makes
it possible for older marketplace contracts to continue functioning even
if we have to perform a token contract migration.
Resolves #376
=> Allow marketplace owner to set the token address

.gitignore, .solcover.js, README.md, contracts/test-alt/ClaimHolderPresigned.js, contracts/test-alt/ClaimVerifier.js, contracts/test-alt/Marketplace.js, contracts/test-alt/UserRegistry.js, contracts/test-alt/_helper.js, contracts/truffle.js, package-lock.json, package.json
This change adds the ability to measure coverage of our main contract
tests by running:
```
npm run test:contracts-coverage
```
The main changes are:
- Adding solidity-coverage configuration
- Extracting the contract path for the contract test deploys, so that
coverage runs use the .sol files that have been instrumented by
solidity-coverage
- Increasing gas for deploys, because coverage-instrumented contracts
are much larger than normal
Resolves #341
=> Support contract tests with solidity-coverage

src/resources/messaging.js
This resolves an issue with the currently-deployed welcome message always being unread when the browser is loaded. 🤦‍♂️
=> Repair message status detection

daemon/indexing/apollo/index.js
I like github/facebook's schema's style better, using just "nodes" for the actual object list. I think it's easier to read when compared with aways duplicating the name of the thing we are accessing.
listings{nodes{id}} <-- new
vs.
listings{listings{id}}  <-- old
Plus it's a little more standard.
@sparrowDom (This change will affect you)
=> 📙 Discovery - switch connections to using “nodes”

src/index.js, src/resources/discovery.js
Dapp already uses a single parameter for discovery server url ( https://github.com/OriginProtocol/origin-dapp/blob/master/src/services/origin.js#L70 ) Lets just change it here also
=> make discovery server url a single parameter

token/lib/token.js, token/scripts/token_cli.js
This adds the `pause` and `unpause` actions to the token CLI, which
pause and unpause token transfers. These may only be called by the token
contract owner.
This also adds `sendTransaction` to the token library, which sends an
Ethereum transaction and polls for the receipt. This is necessary
workaround for an issue where the normal `contract.methods.MyMethod.send()`
function never returns a transaction receipt for certain calls:
https://github.com/INFURA/infura/issues/95
Manually tested the token faucet on Rinkeby & localhost to ensure that it still
works.
=> Add pause & unpause to token_cli

scripts/sample-data.js
Passing the schemaVersion field in the data is no longer necessary when creating a listing. Origin-js picks the current schema.
=> Clean up use of schemaVersion in sample-data.js script

contracts/test-alt/Marketplace.js, src/adapters/marketplace/v00.js, src/services/contract-service.js, test/helpers/contract-service-helper.js
This adds support for the commission to be handled in `createListing`. It also repairs the `contract` reference and `arguments` used in `_getTokenCreateListingParams`.
This still produces an unidentified rpc error:
```
Returned error: Error: Error: [ethjs-rpc] rpc error with payload {
"id":706241195408,
"jsonrpc":"2.0",
"params":[
"0xf9016e068609184e72a0008302752e94345ca3e014aaf5dca488057592ee47305d9b3e1080b9010482857a030000000000000000000000008f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f00000000000000000000000000000000000000000000000542253a126ce40000de40062900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000600386f6684fc0df79d08cdc840f7036f002eb5f54e2d79fddc5be677d …
```
=> Support Commission

scripts/build.js
Contract copy was using async version of pathExists which caused the second predicate in the if statement to be called on a non-existent directory causing build to fail with the following error:
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'contracts/build/contracts'`
Easy fix :tada:
=> Use pathExistsSync

test/service-data-store.test.js
Reruns of service-data-store.test.js would fail, because the save()
in this line:
https://github.com/OriginProtocol/origin-js/blob/master/test/service-data-store.test.js#L107
causes future runs of this line:
https://github.com/OriginProtocol/origin-js/blob/master/test/service-data-store.test.js#L60
to fail.
save() filters out media URLs that seem malformed, and the test URLs
look malformed to it. This unbreaks this test for use in `npm run
test:jsw`.
=> Fix service-data-store.test.js test

src/adapters/marketplace/v00.js
moneyToUnits handles ERC20 currencies in addition to ETH. toWei would be incorrect for currencies with decimals other than 18.
=> Use moneyToUnits instead of toWei

src/adapters/marketplace/_resolver.js, src/resources/marketplace.js
Two repairs to listings:
- passes `opts` to the resolver in order to support `listingsFor` or `purchasesFor`
- includes reviews saved with `OfferData` events (from sellers after `OfferFinalized`)
=> Listings Repairs

contracts/migrations/3_create_sample_listings.js
The way we are currently generating sample listings, makes it impossible to make on offer on them.
For more details see #478 
As a short-term solution, commenting out creation of sample listings on Rinkeby and Ropsten while we work on a solution. For the v0.8.0 Testnet release, we can create those sample listings manually if we want to.
=> Skip sample listing creation on Rinkeby and Ropsten

contracts/contracts/marketplace/v00/Marketplace.sol, contracts/contracts/token/TokenMigration.sol, contracts/contracts/token/WhitelistedPausableToken.sol, contracts/test-alt/_helper.js
Add reason strings to requires
This makes the cause of an EVM revert much clearer to developers. I've
tried to keep the strings short but unambiguous within each function.
I've had to increase the gas limit for contract test deploys, because it
now takes ~5 million gas (compared to ~4 million previously) to deploy
the marketplace contract. This corresponds to a difference in deployment
cost of ~$1.31 USD. The small increase is more than offset by reduction
in developer debugging time. The lowest gas limit I've seen from
Rinkeby, Ropsten, and mainnet is 7 million, so we're OK there.
I also haven't touched contracts/test-alt/contracts
Takes care of #457 for Origin contract code
OpenZeppelin code remains uninstrumented until we vendor it.
=> Add reasons for requires in contracts

src/contractInterface/marketplace/v00_adapter.js
Was a bitch to figure why we were getting an `undefined` for `ipfsHash`. This check will alert us in future if contract events are not working right.
=> Throw error when ipfsHash not found.

src/contractInterface/marketplace/v00_adapter.js
This removes a `null` from the `getPastEvents` query in a few places. This could be what is causing the listings to not show up on demo.staging.originprotocol.com.
The issue is that without events being found, it doesn't set the `ipfsHash` in the `getListing()` call, so no IPFS data is found.
=> Removing extra null in getPastEvents() query

src/ipfsInterface/adapters/listing/v1-listing-adapter.js, src/ipfsInterface/schemas/listing.json, test/fixtures/hawaii-house/hawaii-house.json, test/fixtures/lake-house/lake-house.json, test/fixtures/listing-valid.json, test/fixtures/zinc-house/zinc-house.json, test/ipfs_store.test.js
Per #528, the securityDeposit field in IPFS is not currently being used and should be removed.
=> Remove unused securityDeposit field

contracts/contracts/identity/ERC735.sol, src/contractInterface/users/v00_adapter.js
It's more performant to include the name in the query rather than filtering afterwards. Incidentally, this also seems to resolve the issue in https://github.com/OriginProtocol/origin-dapp/issues/547
=> Specify the event name in getPastEvents call

daemon/indexing/listener/listener.js
Looks like we got a duplicate left over from when we had the v00 marketplace lying around.
EDIT: Or...do we need two entries in this array for some reason? (I've never worked in the listener codebase!)
=> Remove duplicate listener rules

src/resources/marketplace.js
Fix getOffer() arbitrator and affiliate checking
Sometimes, some characters in addresses are upper-cased. Not sure why,
but the net result is that addresses must be compared case
insensitively.  I observed this locally, and it prevented in-progress
offers from showing up on the buyer or seller side.
=> Fix getOffer() arbitrator and affiliate checking

src/resources/messaging.js
Force cookies and OrbitDb to have the same phrase for keys generated.
=> Force the cookies and db to have the same phrase for messages

daemon/indexing/listener/listener.js
Allows the listener to post to HTTP or HTTPS webhook urls. Previously we only supported HTTP.
Probably a lower priority at this time, and can go in after the mainnet beta next week.
=>  🎧 Listener - HTTPS webhook support

src/contractInterface/marketplace/v00_adapter.js
This is overridable. The previous default was 24 hours from offer
creation, which is too short.
=> Make offers finalize 30 days after acceptance (by default)

src/contractInterface/marketplace/resolver.js, src/contractInterface/marketplace/v00_adapter.js, src/contractInterface/users/resolver.js, src/contractInterface/users/v00_adapter.js, src/index.js, src/resources/attestations.js, src/resources/users.js
Stopgap for speeding up scanning of events for the marketplace contract,
particularly for Rinkeby and Mainet. Restricts getPastEvents to a recent
block number for the Marketplace contract.
Goes with OriginProtocol/origin-dapp#656 and OriginProtocol/origin-box#102
=> Add block epoch

src/contractInterface/marketplace/v00_adapter.js
Add function to console.log a listing
Example use:
```
await originTest.marketplace.resolver.currentAdapter.logListing(4)
```
Pulls in all relevant Solidity events, Solidity structs, and IPFS
objects. The intention is to give developers a useful tool that
shows a consolidated form of the on-chain and off-chain state
of a listing.
=> Add function to console.log a listing

contracts/contracts/identity/ClaimHolderLibrary.sol, contracts/migrations/11_update_claim_holder_library.js, test/resource_users.test.js
The 5th atttestation will be at i=4 (0-indexed). 3 * 65 = 195 (no problem). 4 * 65 = 260... This is a problem because i is a uint8; 260 > 256, therefore overflow. :grimacing:
Thanks @crazybuster for figuring this out.
We do not need to rerun migrations, but we _do_ need to update origin-js with this fix, so that new identities that users create do not have this bug.
Resolves #413
=> Fix overflow bug when adding more than 4 attestations

src/resources/marketplace.js, test/resource_marketplace.test.js
See linked issue below. This prevents invalid offers from causing the `getNotifications` method to crash.
Resolves https://github.com/OriginProtocol/origin-js/issues/558
=> Ignore notifications that include invalid offers
